# Generated by Django 6.0.5 on 2026-06-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_rest_replication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="synccursor",
            name="snapshot_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the initial snapshot phase completed. Null = not yet bootstrapped.",
                null=True,
            ),
        ),
    ]
